# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 4443:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: tunay
      POSTGRES_DB: blog

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080